enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "apk"
excluded-patches = "'Downloads' 'Swipe controls' 'Always repeat'"
included-patches = "'Custom branding'"
patcher-args = "-OappName='YouTube'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Reddit]
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
apkmirror-dpi = "120-640dpi"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'Change version code'"

[Twitter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"

[Twitch]
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
version = "auto"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

[Tiktok]
enabled = false
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
included-patches = "'SIM spoof' 'Change version code'"
version = "auto"
arch = "arm64-v8a"

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'Change version code' 'Custom theme'"
arch = "arm64-v8a"
